# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/perfiles.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(710, 520)
        Form.setMinimumSize(QtCore.QSize(710, 520))
        Form.setMaximumSize(QtCore.QSize(710, 520))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/croquis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.addPerfil = QtGui.QPushButton(Form)
        self.addPerfil.setGeometry(QtCore.QRect(640, 10, 30, 20))
        self.addPerfil.setMaximumSize(QtCore.QSize(30, 20))
        self.addPerfil.setObjectName(_fromUtf8("addPerfil"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 94, 691, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabBajas = QtGui.QWidget()
        self.tabBajas.setObjectName(_fromUtf8("tabBajas"))
        self.bajasActivada = QtGui.QCheckBox(self.tabBajas)
        self.bajasActivada.setGeometry(QtCore.QRect(10, 10, 70, 17))
        self.bajasActivada.setObjectName(_fromUtf8("bajasActivada"))
        self.bajasModo = QtGui.QComboBox(self.tabBajas)
        self.bajasModo.setGeometry(QtCore.QRect(470, 10, 201, 22))
        self.bajasModo.setObjectName(_fromUtf8("bajasModo"))
        self.label_5 = QtGui.QLabel(self.tabBajas)
        self.label_5.setGeometry(QtCore.QRect(433, 13, 31, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.bajasPrecio = QtGui.QLineEdit(self.tabBajas)
        self.bajasPrecio.setGeometry(QtCore.QRect(83, 39, 101, 20))
        self.bajasPrecio.setObjectName(_fromUtf8("bajasPrecio"))
        self.label_7 = QtGui.QLabel(self.tabBajas)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.bajasLiq = QtGui.QLineEdit(self.tabBajas)
        self.bajasLiq.setGeometry(QtCore.QRect(571, 39, 101, 20))
        self.bajasLiq.setObjectName(_fromUtf8("bajasLiq"))
        self.label_9 = QtGui.QLabel(self.tabBajas)
        self.label_9.setGeometry(QtCore.QRect(498, 40, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tabBajas)
        self.label_10.setGeometry(QtCore.QRect(253, 41, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.bajasMin = QtGui.QLineEdit(self.tabBajas)
        self.bajasMin.setGeometry(QtCore.QRect(332, 40, 101, 20))
        self.bajasMin.setObjectName(_fromUtf8("bajasMin"))
        self.bajasTablaTramos = QtGui.QTableWidget(self.tabBajas)
        self.bajasTablaTramos.setGeometry(QtCore.QRect(10, 120, 661, 211))
        self.bajasTablaTramos.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.bajasTablaTramos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.bajasTablaTramos.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.bajasTablaTramos.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.bajasTablaTramos.setObjectName(_fromUtf8("bajasTablaTramos"))
        self.bajasTablaTramos.setColumnCount(0)
        self.bajasTablaTramos.setRowCount(0)
        self.addTramoBaja = QtGui.QPushButton(self.tabBajas)
        self.addTramoBaja.setGeometry(QtCore.QRect(610, 90, 30, 20))
        self.addTramoBaja.setMaximumSize(QtCore.QSize(30, 20))
        self.addTramoBaja.setObjectName(_fromUtf8("addTramoBaja"))
        self.delTramoBajas = QtGui.QPushButton(self.tabBajas)
        self.delTramoBajas.setGeometry(QtCore.QRect(640, 90, 30, 20))
        self.delTramoBajas.setMaximumSize(QtCore.QSize(30, 20))
        self.delTramoBajas.setObjectName(_fromUtf8("delTramoBajas"))
        self.bajasIncPorcentaje = QtGui.QLineEdit(self.tabBajas)
        self.bajasIncPorcentaje.setGeometry(QtCore.QRect(571, 64, 101, 20))
        self.bajasIncPorcentaje.setObjectName(_fromUtf8("bajasIncPorcentaje"))
        self.bajasIncMin = QtGui.QLineEdit(self.tabBajas)
        self.bajasIncMin.setGeometry(QtCore.QRect(332, 64, 101, 20))
        self.bajasIncMin.setObjectName(_fromUtf8("bajasIncMin"))
        self.label_11 = QtGui.QLabel(self.tabBajas)
        self.label_11.setGeometry(QtCore.QRect(498, 64, 71, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tabBajas)
        self.label_12.setGeometry(QtCore.QRect(249, 64, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tabWidget.addTab(self.tabBajas, _fromUtf8(""))
        self.tabGraf = QtGui.QWidget()
        self.tabGraf.setObjectName(_fromUtf8("tabGraf"))
        self.label_13 = QtGui.QLabel(self.tabGraf)
        self.label_13.setGeometry(QtCore.QRect(433, 13, 31, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tabGraf)
        self.label_14.setGeometry(QtCore.QRect(253, 41, 81, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.grafPrecio = QtGui.QLineEdit(self.tabGraf)
        self.grafPrecio.setGeometry(QtCore.QRect(83, 39, 101, 20))
        self.grafPrecio.setObjectName(_fromUtf8("grafPrecio"))
        self.grafModo = QtGui.QComboBox(self.tabGraf)
        self.grafModo.setGeometry(QtCore.QRect(470, 10, 201, 22))
        self.grafModo.setObjectName(_fromUtf8("grafModo"))
        self.grafActivada = QtGui.QCheckBox(self.tabGraf)
        self.grafActivada.setGeometry(QtCore.QRect(10, 10, 70, 17))
        self.grafActivada.setObjectName(_fromUtf8("grafActivada"))
        self.grafMin = QtGui.QLineEdit(self.tabGraf)
        self.grafMin.setGeometry(QtCore.QRect(332, 40, 101, 20))
        self.grafMin.setObjectName(_fromUtf8("grafMin"))
        self.label_15 = QtGui.QLabel(self.tabGraf)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tabGraf)
        self.label_16.setGeometry(QtCore.QRect(498, 40, 71, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.grafLiq = QtGui.QLineEdit(self.tabGraf)
        self.grafLiq.setGeometry(QtCore.QRect(571, 39, 101, 20))
        self.grafLiq.setObjectName(_fromUtf8("grafLiq"))
        self.grafTablaTramos = QtGui.QTableWidget(self.tabGraf)
        self.grafTablaTramos.setGeometry(QtCore.QRect(10, 120, 661, 211))
        self.grafTablaTramos.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.grafTablaTramos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.grafTablaTramos.setObjectName(_fromUtf8("grafTablaTramos"))
        self.grafTablaTramos.setColumnCount(0)
        self.grafTablaTramos.setRowCount(0)
        self.addTramoGraf = QtGui.QPushButton(self.tabGraf)
        self.addTramoGraf.setGeometry(QtCore.QRect(610, 90, 30, 20))
        self.addTramoGraf.setMaximumSize(QtCore.QSize(30, 20))
        self.addTramoGraf.setObjectName(_fromUtf8("addTramoGraf"))
        self.delTramoGraf = QtGui.QPushButton(self.tabGraf)
        self.delTramoGraf.setGeometry(QtCore.QRect(640, 90, 30, 20))
        self.delTramoGraf.setMaximumSize(QtCore.QSize(30, 20))
        self.delTramoGraf.setObjectName(_fromUtf8("delTramoGraf"))
        self.grafIncMin = QtGui.QLineEdit(self.tabGraf)
        self.grafIncMin.setGeometry(QtCore.QRect(332, 64, 101, 20))
        self.grafIncMin.setObjectName(_fromUtf8("grafIncMin"))
        self.label_23 = QtGui.QLabel(self.tabGraf)
        self.label_23.setGeometry(QtCore.QRect(498, 64, 71, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.grafIncPorcentaje = QtGui.QLineEdit(self.tabGraf)
        self.grafIncPorcentaje.setGeometry(QtCore.QRect(571, 64, 101, 20))
        self.grafIncPorcentaje.setObjectName(_fromUtf8("grafIncPorcentaje"))
        self.label_24 = QtGui.QLabel(self.tabGraf)
        self.label_24.setGeometry(QtCore.QRect(249, 64, 81, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.tabWidget.addTab(self.tabGraf, _fromUtf8(""))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.label_17 = QtGui.QLabel(self.tabGeneral)
        self.label_17.setGeometry(QtCore.QRect(433, 13, 31, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tabGeneral)
        self.label_18.setGeometry(QtCore.QRect(253, 41, 81, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.generalPrecio = QtGui.QLineEdit(self.tabGeneral)
        self.generalPrecio.setGeometry(QtCore.QRect(83, 39, 101, 20))
        self.generalPrecio.setObjectName(_fromUtf8("generalPrecio"))
        self.generalModo = QtGui.QComboBox(self.tabGeneral)
        self.generalModo.setGeometry(QtCore.QRect(470, 10, 201, 22))
        self.generalModo.setObjectName(_fromUtf8("generalModo"))
        self.generalActivada = QtGui.QCheckBox(self.tabGeneral)
        self.generalActivada.setGeometry(QtCore.QRect(10, 10, 70, 17))
        self.generalActivada.setObjectName(_fromUtf8("generalActivada"))
        self.generalMin = QtGui.QLineEdit(self.tabGeneral)
        self.generalMin.setGeometry(QtCore.QRect(332, 40, 101, 20))
        self.generalMin.setObjectName(_fromUtf8("generalMin"))
        self.label_19 = QtGui.QLabel(self.tabGeneral)
        self.label_19.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tabGeneral)
        self.label_20.setGeometry(QtCore.QRect(498, 40, 71, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.generalLiq = QtGui.QLineEdit(self.tabGeneral)
        self.generalLiq.setGeometry(QtCore.QRect(571, 39, 101, 20))
        self.generalLiq.setObjectName(_fromUtf8("generalLiq"))
        self.generalTablaTramos = QtGui.QTableWidget(self.tabGeneral)
        self.generalTablaTramos.setGeometry(QtCore.QRect(10, 120, 661, 211))
        self.generalTablaTramos.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.generalTablaTramos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.generalTablaTramos.setObjectName(_fromUtf8("generalTablaTramos"))
        self.generalTablaTramos.setColumnCount(0)
        self.generalTablaTramos.setRowCount(0)
        self.addTramoGen = QtGui.QPushButton(self.tabGeneral)
        self.addTramoGen.setGeometry(QtCore.QRect(610, 90, 30, 20))
        self.addTramoGen.setMaximumSize(QtCore.QSize(30, 20))
        self.addTramoGen.setObjectName(_fromUtf8("addTramoGen"))
        self.delTramoGen = QtGui.QPushButton(self.tabGeneral)
        self.delTramoGen.setGeometry(QtCore.QRect(640, 90, 30, 20))
        self.delTramoGen.setMaximumSize(QtCore.QSize(30, 20))
        self.delTramoGen.setObjectName(_fromUtf8("delTramoGen"))
        self.genIncPorcentaje = QtGui.QLineEdit(self.tabGeneral)
        self.genIncPorcentaje.setGeometry(QtCore.QRect(571, 64, 101, 20))
        self.genIncPorcentaje.setObjectName(_fromUtf8("genIncPorcentaje"))
        self.label_25 = QtGui.QLabel(self.tabGeneral)
        self.label_25.setGeometry(QtCore.QRect(249, 64, 81, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.genIncMin = QtGui.QLineEdit(self.tabGeneral)
        self.genIncMin.setGeometry(QtCore.QRect(332, 64, 101, 20))
        self.genIncMin.setObjectName(_fromUtf8("genIncMin"))
        self.label_26 = QtGui.QLabel(self.tabGeneral)
        self.label_26.setGeometry(QtCore.QRect(498, 64, 71, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.tabWidget.addTab(self.tabGeneral, _fromUtf8(""))
        self.tabPartida = QtGui.QWidget()
        self.tabPartida.setObjectName(_fromUtf8("tabPartida"))
        self.partidaActivada = QtGui.QCheckBox(self.tabPartida)
        self.partidaActivada.setGeometry(QtCore.QRect(10, 10, 70, 17))
        self.partidaActivada.setObjectName(_fromUtf8("partidaActivada"))
        self.tabWidget.addTab(self.tabPartida, _fromUtf8(""))
        self.tabCampos = QtGui.QWidget()
        self.tabCampos.setObjectName(_fromUtf8("tabCampos"))
        self.CamposTabla = QtGui.QTableWidget(self.tabCampos)
        self.CamposTabla.setGeometry(QtCore.QRect(7, 75, 671, 261))
        self.CamposTabla.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.CamposTabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.CamposTabla.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.CamposTabla.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.CamposTabla.setObjectName(_fromUtf8("CamposTabla"))
        self.CamposTabla.setColumnCount(0)
        self.CamposTabla.setRowCount(0)
        self.but_masCampo = QtGui.QPushButton(self.tabCampos)
        self.but_masCampo.setGeometry(QtCore.QRect(618, 50, 30, 23))
        self.but_masCampo.setMaximumSize(QtCore.QSize(30, 16777215))
        self.but_masCampo.setObjectName(_fromUtf8("but_masCampo"))
        self.but_menosCampo = QtGui.QPushButton(self.tabCampos)
        self.but_menosCampo.setGeometry(QtCore.QRect(648, 50, 30, 23))
        self.but_menosCampo.setMinimumSize(QtCore.QSize(30, 0))
        self.but_menosCampo.setMaximumSize(QtCore.QSize(30, 16777215))
        self.but_menosCampo.setObjectName(_fromUtf8("but_menosCampo"))
        self.tabWidget.addTab(self.tabCampos, _fromUtf8(""))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 41, 55, 16))
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.codigo = QtGui.QLineEdit(Form)
        self.codigo.setGeometry(QtCore.QRect(380, 40, 80, 20))
        self.codigo.setMaximumSize(QtCore.QSize(80, 16777215))
        self.codigo.setObjectName(_fromUtf8("codigo"))
        self.comboPerfiles = QtGui.QComboBox(Form)
        self.comboPerfiles.setGeometry(QtCore.QRect(67, 10, 571, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPerfiles.sizePolicy().hasHeightForWidth())
        self.comboPerfiles.setSizePolicy(sizePolicy)
        self.comboPerfiles.setObjectName(_fromUtf8("comboPerfiles"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 28, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(340, 41, 37, 16))
        self.label_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.provincia = QtGui.QLineEdit(Form)
        self.provincia.setGeometry(QtCore.QRect(522, 40, 181, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.provincia.sizePolicy().hasHeightForWidth())
        self.provincia.setSizePolicy(sizePolicy)
        self.provincia.setObjectName(_fromUtf8("provincia"))
        self.delPerfil = QtGui.QPushButton(Form)
        self.delPerfil.setGeometry(QtCore.QRect(670, 10, 30, 20))
        self.delPerfil.setMaximumSize(QtCore.QSize(30, 20))
        self.delPerfil.setObjectName(_fromUtf8("delPerfil"))
        self.organismo = QtGui.QLineEdit(Form)
        self.organismo.setGeometry(QtCore.QRect(70, 40, 261, 20))
        self.organismo.setObjectName(_fromUtf8("organismo"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(470, 41, 47, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.but_guardar = QtGui.QPushButton(Form)
        self.but_guardar.setGeometry(QtCore.QRect(320, 474, 75, 23))
        self.but_guardar.setObjectName(_fromUtf8("but_guardar"))
        self.comboTipo = QtGui.QComboBox(Form)
        self.comboTipo.setGeometry(QtCore.QRect(528, 66, 171, 22))
        self.comboTipo.setObjectName(_fromUtf8("comboTipo"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(429, 66, 101, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Administrador de perfiles", None))
        self.addPerfil.setText(_translate("Form", "+", None))
        self.bajasActivada.setText(_translate("Form", "Activada", None))
        self.label_5.setText(_translate("Form", "Modo:", None))
        self.label_7.setText(_translate("Form", "Precio unitario:", None))
        self.label_9.setText(_translate("Form", "% liquidación:", None))
        self.label_10.setText(_translate("Form", "Min. liquidación:", None))
        self.addTramoBaja.setText(_translate("Form", "+", None))
        self.delTramoBajas.setText(_translate("Form", "-", None))
        self.label_11.setText(_translate("Form", "% inc padrón:", None))
        self.label_12.setText(_translate("Form", "Min. inc. padrón:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBajas), _translate("Form", "Facturación de bajas", None))
        self.label_13.setText(_translate("Form", "Modo:", None))
        self.label_14.setText(_translate("Form", "Min. liquidación:", None))
        self.grafActivada.setText(_translate("Form", "Activada", None))
        self.label_15.setText(_translate("Form", "Precio unitario:", None))
        self.label_16.setText(_translate("Form", "% liquidación:", None))
        self.addTramoGraf.setText(_translate("Form", "+", None))
        self.delTramoGraf.setText(_translate("Form", "-", None))
        self.label_23.setText(_translate("Form", "% inc padrón:", None))
        self.label_24.setText(_translate("Form", "Min. inc. padrón:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGraf), _translate("Form", "Facturación de ajustes gráficos", None))
        self.label_17.setText(_translate("Form", "Modo:", None))
        self.label_18.setText(_translate("Form", "Min. liquidación:", None))
        self.generalActivada.setText(_translate("Form", "Activada", None))
        self.label_19.setText(_translate("Form", "Precio unitario:", None))
        self.label_20.setText(_translate("Form", "% liquidación:", None))
        self.addTramoGen.setText(_translate("Form", "+", None))
        self.delTramoGen.setText(_translate("Form", "-", None))
        self.label_25.setText(_translate("Form", "Min. inc. padrón:", None))
        self.label_26.setText(_translate("Form", "% inc padrón:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("Form", "Facturación general", None))
        self.partidaActivada.setText(_translate("Form", "Activada", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPartida), _translate("Form", "Facturación partida presupuestaria", None))
        self.but_masCampo.setText(_translate("Form", "+", None))
        self.but_menosCampo.setText(_translate("Form", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCampos), _translate("Form", "Campos", None))
        self.label_2.setText(_translate("Form", "Organismo:", None))
        self.label.setText(_translate("Form", "Perfil:", None))
        self.label_3.setText(_translate("Form", "Código:", None))
        self.delPerfil.setText(_translate("Form", "-", None))
        self.label_4.setText(_translate("Form", "Provincia:", None))
        self.but_guardar.setText(_translate("Form", "Guardar", None))
        self.label_6.setText(_translate("Form", "Tipo de facturación:", None))

import ficheros_rc
